# Generated by Django 3.0.3 on 2020-02-10 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20200209_0350'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='catName',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='news',
            name='newCategory',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='news',
            name='newShow',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
