# Generated by Django 3.0.3 on 2020-02-10 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20200210_0642'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='catName',
            new_name='catId',
        ),
    ]
