# Generated by Django 3.0.3 on 2020-02-10 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20200210_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='pic',
            field=models.CharField(max_length=2000),
        ),
    ]
