# Generated by Django 3.0.3 on 2020-02-10 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_auto_20200210_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='pic',
            field=models.FileField(upload_to=''),
        ),
    ]
