# Generated by Django 3.0.3 on 2020-02-13 21:17

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_auto_20200211_0715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='newBody',
            field=ckeditor.fields.RichTextField(max_length=200),
        ),
    ]
