# Generated by Django 3.0.3 on 2020-02-14 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_auto_20200213_1317'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='picname',
            new_name='picName',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='picurl',
            new_name='picUrl',
        ),
    ]
