# Generated by Django 3.0.3 on 2020-02-14 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_auto_20200214_0242'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='OcatId',
            field=models.CharField(default=0, max_length=50),
        ),
    ]
