# Generated by Django 3.0.3 on 2020-02-14 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_news_ocatid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='picName',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='news',
            name='picUrl',
            field=models.CharField(max_length=5000),
        ),
    ]
