# Generated by Django 3.0.3 on 2020-02-14 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0011_auto_20200214_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='OcatId',
            field=models.CharField(default=1, max_length=50),
        ),
        migrations.AlterField(
            model_name='news',
            name='catId',
            field=models.CharField(default=1, max_length=50),
        ),
    ]
