# Generated by Django 3.0.3 on 2020-02-15 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0012_auto_20200214_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='OcatId',
            field=models.CharField(max_length=50),
        ),
    ]
