# Generated by Django 3.0.3 on 2020-02-19 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contantform', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contantform',
            new_name='Cont',
        ),
        migrations.RenameField(
            model_name='cont',
            old_name='emial',
            new_name='Email',
        ),
        migrations.RenameField(
            model_name='cont',
            old_name='wibsite',
            new_name='website',
        ),
    ]
