# Generated by Django 3.0.3 on 2020-02-08 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='main',
            name='about',
            field=models.CharField(default=15, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='main',
            name='age',
            field=models.CharField(default=15, max_length=15),
            preserve_default=False,
        ),
    ]
