# Generated by Django 3.0.3 on 2020-02-09 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200208_1328'),
    ]

    operations = [
        migrations.RenameField(
            model_name='main',
            old_name='age',
            new_name='pagefa',
        ),
        migrations.AddField(
            model_name='main',
            name='pagetw',
            field=models.CharField(default=0.1, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='main',
            name='pageyt',
            field=models.CharField(default=15, max_length=15),
            preserve_default=False,
        ),
    ]
