# Generated by Django 3.0.3 on 2020-02-09 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_main_name_set'),
    ]

    operations = [
        migrations.AddField(
            model_name='main',
            name='pageTe',
            field=models.CharField(default=0, max_length=20),
        ),
    ]
