# Generated by Django 3.0.3 on 2020-02-17 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_main_pagelink'),
    ]

    operations = [
        migrations.AddField(
            model_name='main',
            name='picname',
            field=models.TextField(default='', max_length=22),
        ),
        migrations.AddField(
            model_name='main',
            name='picurl',
            field=models.TextField(default='', max_length=22),
        ),
        migrations.AlterField(
            model_name='main',
            name='about',
            field=models.TextField(max_length=10000),
        ),
    ]
